version: '3'

networks:
    docker_network:

services:
    
    nginx:
        container_name: nginx
        build: 
            context: ./requirements/nginx
        image: nginx
        networks:
            - docker_network
        ports:
            - "443:443"
        volumes:
            - wp_data:/var/www/html
        restart: always
    #mysql:
    #    container_name: mariadb
    #    image: mariadb:v_final
    #    volumes:
    #        -db_data:/var/lib/mysql
    #    env_file:
    #        - .env
    #    restart: always
    #wordpress:
    #    container_name: wordpress
    #    image: wordpress:php7.3-fpm-alpine
    #    volumes:
    #        - wp_data:/var/www/html
    #    depends_on:
    #        - mysql
    #    env_file:
    #        .env
    #    links:
    #        - mysql
    #    restart: always


volumes:
    #db_data:
    #    driver: local
    #    driver_opts:
    #        type: volume
    #        o : bind
    #        device : /home/jdamoise/data/mysql
    wp_data:
        driver: local
        driver_opts:
            type: volume
            o : bind
            device : /home/jdamoise/data/wordpress