version: '3'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/jdamoise/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/jdamoise/data/wordpress
      type: volume
      o: bind

networks:
  docker-network:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - docker-network
    ports:
      - "443:443"
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - docker-network
    env_file: 
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - docker-network
    env_file: 
      - .env
    restart: unless-stopped