version: '3'

networks:
    docker_network:

services:
    
    nginx:
        container_name: nginx
        build: 
            context: ./requirements/nginx
        image: nginx
        networks:
            - docker_network
        ports:
            - "443:443"
        volumes:
            - wp_data:/var/www/wordpress
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        image: mariadb
        volumes:
            - db_data:/var/lib/mysql
        networks: 
            - docker_network
        env_file: 
            .env
        restart: unless-stopped

    wordpress:
        container_name: wordpress
        image: wordpress
        build:
            context: ./requirements/wordpress
        volumes:
            - wp_data:/var/www/wordpress
        depends_on:
            - mariadb
        networks:
            - docker_network
        env_file:
            .env
        restart: unless-stopped
volumes:
    db_data:
        driver: local
        driver_opts:
            type: volume
            o : bind
            device : /home/jdamoise/data/mariadb
    wp_data:
        driver: local
        driver_opts:
            type: volume
            o : bind
            device : /home/jdamoise/data/wordpress